[build]
  command = "npm run build"
  publish = "build"

# Environment variables should be set in the Netlify dashboard
# DO NOT include sensitive information in this file

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
